modLoader = "javafml"
loaderVersion = "${neoforge_loader_version_range}"
issueTrackerURL = "https://github.com/CloudG360/warptocrosshair/issues"
license = "MIT"

[[mods]]
modId = "warptocrosshair"
version = "${version}"
displayName = "Warp-To-Crosshair"
authors = "CG360"
description = "Zip around with middle-click (or whatever you set it to, it's configurable!)"
logoFile = "assets/warptocrosshair/icon.png"
displayURL = "https://github.com/CloudG360/warptocrosshair"
displayTest = "IGNORE_ALL_VERSION"

[[mixins]]
config = 'warptocrosshair.mixins.json'

[[dependencies.warptocrosshair]]
modId = "neoforge"
type = "required"
versionRange = "${neoforge_compatibility_range}"
ordering = "NONE"
side = "CLIENT"

[[dependencies.warptocrosshair]]
modId = "minecraft"
type = "required"
versionRange = "${supported_minecraft_versions_neoforge}"
ordering = "NONE"
side = "CLIENT"

[[dependencies.warptocrosshair]]
modId = "yet_another_config_lib_v3"
mandatory = true
versionRange = "[${yacl_version},)"
ordering = "NONE"
side = "CLIENT"